### ISSUE TITLE
Running Tests

### ISSUE THREAD

**Issue by balasankarc** [fnando/notifier#15]
Hi,
May I know how to run tests for this gem? The Rakefile points to the test folder but there is no such folder in the repo.
Also, it seems building depends on RSpec >~ 3.0. Also mention that in the gemspec.

PS : I am maintaining the Debian package of this gem.

**Comment by fnando** [comment]
Is this still an issue? If so, I migrated to Minitest. You can run `bundle install` to install dependencies and then `rake`.
