### ISSUE TITLE
Add "subtitle" support for terminal-notifier

### ISSUE THREAD

**Issue by eriknomitch** [fnando/notifier#16]
terminal-notifier supports a `-subtitle` flag which is very helpful and would be great to support.

For other notifiers without a subtitle option, maybe the subtitle could be prepended to the message with a delimiter when `subtitle:` is passed to `Notifier.notify`.

What do you think?

Edit: Just FYI I'm using this for [notify-push](https://github.com/eriknomitch/notify-push).

Erik

**Comment by fnando** [comment]
Added through 11caa066d5ae3783bf4ca83f473849d64628f62d.

Sorry for taking this long.
